#!/bin/sh

TYPE=Debug

if [ ! -z "$1" ]; then
TYPE="$1"
fi

mkdir -p build/$TYPE
cd build/$TYPE
cmake -DCMAKE_BUILD_TYPE=$TYPE ../..
make -k csmapfx-pot-update csmapfx-po-update csmapfx-i18n csmapfx

