#!/bin/bash
set -e
test -e .env && eval $(cat .env)
BRANCH=$(git status -s -b | head -1 | cut -d\  -f 2 | sed 's/\..*//')
VERSION=$(git describe --tags --match 'v*.*.*')
echo "submitting version $BRANCH-$VERSION"
cmake -S . -B out -DCMAKE_BUILD_TYPE=Debug
cd out
cov-build --dir cov-int make
tar czf csmapfx.tgz cov-int
curl -k --form token=${COV_TOKEN} \
  --form email=enno.rehling@gmail.com \
  --form file=@csmapfx.tgz \
  --form version="$BRANCH-$VERSION" \
  --form description="CsMap coverity check" \
  https://scan.coverity.com/builds?project=ennorehling%2Fcsmapfx
