#!/bin/sh
version=$(grep 'define CSMAP_APP_VERSION ' version.h | sed 's/,/./g' | awk '{ print $3$4$5 }')
git clean -d -f -x
tar c --exclude-vcs-ignores \
	--exclude-vcs \
	--exclude=debian \
	-Jvf ../csmapfx_$version.orig.tar.xz --xform='s/./csmapfx-$version/' .
dpkg-buildpackage -rfakeroot -D -us -uc

