#!/bin/sh
version=0.6.5
git clean -d -f -x
tar c --exclude-vcs-ignores \
	--exclude-vcs \
	--exclude=debian \
	-Jvf ../csmapfx_$version.orig.tar.xz --xform='s/./csmapfx-$version/' .
dpkg-buildpackage -rfakeroot -D -us -uc

