name: release
on:
  push:
    tags:
      - 'v*'
    branches:
      - gh
jobs:
  build-deb:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        dist:
          - bullseye
        arch:
          - amd64
          - i386
          - arm64
          - armhf
    steps:
      - name: Get latest CMake and ninja
        uses: lukka/get-cmake@latest
      - name: Update APT
        run: sudo apt update
      - name: Install Dependencies
        run: sudo apt install --assume-yes libfox-1.6-dev libphysfs-dev libcurl4-openssl-dev
      - name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: true
      - name: Build Debian Package
        uses: ennorehling/action-debian-package@v2.2
        with:
           os_distribution: ${{ matrix.dist }}
           cpu_architecture: ${{ matrix.arch }}
           artifacts_directory: artifacts
      - name: Upload to Packagecloud
        continue-on-error: true
        uses: danielmundi/upload-packagecloud@v1
        with:
          package-name: artifacts/csmapfx_*_${{ matrix.arch }}.deb
          packagecloud-username: enno
          packagecloud-repo: eressea
          packagecloud-distrib: debian/${{ matrix.dist }}
          packagecloud-token: ${{ secrets.PACKAGECLOUD_TOKEN }}
